name: leeseidenberg
favicon: null
layout_spectrum: 0.91002
typography_spectrum: 0.42314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e8ed'
    - '#b6bac5'
    - '#2150ae'
    - '#87878f'
    - '#131927'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.4890718476381153
  rhythmicContrast: 0.6408030826132745
purpose: []
